USE CLG;

CREATE TABLE student(
id INT AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
marks INT NOT NULL,
grade VARCHAR(1),
city VARCHAR(50),
PRIMARY KEY(id)
);

INSERT INTO student(name,marks,grade,city) VALUES ("anil",78,"C","Pune"),
("bhumika",93,"A","mumbai"),
("chetan",85,"B","mumbai"),
("dhruv",96,"A","delhi"),
("emanuel",12,"F","delhi"),
("farah",82,"B","delhi");

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD COLUMN AGE INT NOT NULL DEFAULT 21;

ALTER TABLE STUDENT MODIFY COLUMN AGE VARCHAR(2);

INSERT INTO STUDENT(NAME,MARKS,GRADE,CITY,STD_AGE) VALUES ("SUBHANKAR",90,"O","BHAWANIPATNA",100);

ALTER TABLE STUDENT CHANGE AGE STD_AGE INT;

DELETE FROM STUDENT WHERE STD_AGE=1;

ALTER TABLE STUDENT DROP COLUMN STD_AGE;

ALTER TABLE STD RENAME TO STUDENT;

TRUNCATE TABLE STUDENT;
