use XYZ;
SHOW TABLES;

SELECT * FROM empinfo;

CREATE TABLE EMP(
id INT PRIMARY KEY,
name VARCHAR(50),
salary INT DEFAULT 50000
);

INSERT INTO EMP(id,name) VALUES (2,"SUBHANKAR");

SELECT * FROM EMP;

UPDATE EMP
SET salary = 50000
WHERE id = 1;


CREATE TABLE EMP1(
id INT,
name VARCHAR(50),
PRIMARY KEY(id,name)
);
INSERT INTO EMP1 VALUES (1,"SUBHANKAR");
INSERT INTO EMP1 VALUES (2,"SUBHANKAR");

SELECT * FROM EMP1;