use clg;

CREATE TABLE dept(
id INT AUTO_INCREMENT,
NAME VARCHAR(20),
PRIMARY KEY(ID)
)AUTO_INCREMENT=101;

UPDATE DEPT SET ID=111 WHERE NAME="ENGLISH";

SELECT * FROM DEPT;

INSERT DEPT(NAME) VALUES ("ENGLISH"),("IT");
DELETE  FROM DEPT WHERE NAME="ENGLISH"; 
SELECT * FROM DEPT;

CREATE TABLE TEACHER(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
DEPT_ID INT,
FOREIGN KEY(DEPT_ID) REFERENCES DEPT(ID)
ON DELETE CASCADE
ON UPDATE CASCADE
)AUTO_INCREMENT=101;

DROP TABLE TEACHER;


SELECT * FROM TEACHER;

INSERT INTO TEACHER(NAME,DEPT_ID) VALUES("ADAM",101),("EVE",102);


SET SQL_SAFE_UPDATES=0;