CREATE DATABASE JOINS;
 USE JOINS;
 
 
CREATE TABLE STUDENT(
STUDENT_ID INT AUTO_INCREMENT,
NAME VARCHAR(20),
PRIMARY KEY(STUDENT_ID)
)AUTO_INCREMENT=101;

INSERT INTO STUDENT(NAME) VALUES("ADAM"),
("BOB"),("CASEY");

SELECT * FROM STUDENT;

CREATE TABLE COURSE(
STUDENT_ID INT PRIMARY KEY,
COURSE VARCHAR(20)
);

INSERT INTO COURSE(STUDENT_ID,COURSE) VALUES(102,"ENGLISH"),(105,"MATH"),(103,"SCIENCE"),(107,"COMPUTER SCIENCE");

SELECT * FROM COURSE;

-- INNER JOIN
SELECT * FROM STUDENT
INNER JOIN COURSE
ON STUDENT.STUDENT_ID=COURSE.STUDENT_ID;

-- LEFT JOIN
SELECT * FROM STUDENT AS S 
LEFT JOIN COURSE AS C 
ON S.STUDENT_ID = C.STUDENT_ID;

-- RIGHT JOIN
SELECT * FROM STUDENT AS S 
RIGHT JOIN COURSE AS C 
ON S.STUDENT_ID=C.STUDENT_ID;

-- FULL JOIN
SELECT * FROM STUDENT AS S 
LEFT JOIN COURSE AS C 
ON S.STUDENT_ID = C.STUDENT_ID
UNION
SELECT * FROM STUDENT AS S 
RIGHT JOIN COURSE AS C 
ON S.STUDENT_ID=C.STUDENT_ID;

select * from student as a left join course as b on a.student_id=b.student_id
where b.student_id is null;

select * from student as a right join course as b on a.student_id=b.student_id
where a.student_id is null;