CREATE DATABASE JOINS;

USE JOINS;
 
 
CREATE TABLE STUDENT(
STUDENT_ID INT AUTO_INCREMENT,
NAME VARCHAR(20),
PRIMARY KEY(STUDENT_ID)
)AUTO_INCREMENT=101;

INSERT INTO STUDENT(NAME) VALUES("ADAM"),
("BOB"),("CASEY");

SELECT * FROM STUDENT;

CREATE TABLE COURSE(
STUDENT_ID INT PRIMARY KEY,
COURSE VARCHAR(20)
);

INSERT INTO COURSE(STUDENT_ID,COURSE) VALUES(102,"ENGLISH"),(105,"MATH"),(103,"SCIENCE"),(107,"COMPUTER SCIENCE");

SELECT * FROM COURSE;

-- INNER JOIN
SELECT * FROM STUDENT
INNER JOIN COURSE
ON STUDENT.STUDENT_ID=COURSE.STUDENT_ID;

-- LEFT JOIN
SELECT * FROM STUDENT AS S 
LEFT JOIN COURSE AS C 
ON S.STUDENT_ID = C.STUDENT_ID;

-- RIGHT JOIN
SELECT * FROM STUDENT AS S 
RIGHT JOIN COURSE AS C 
ON S.STUDENT_ID=C.STUDENT_ID;

-- FULL JOIN
SELECT * FROM STUDENT AS S 
LEFT JOIN COURSE AS C 
ON S.STUDENT_ID = C.STUDENT_ID
UNION
SELECT * FROM STUDENT AS S 
RIGHT JOIN COURSE AS C 
ON S.STUDENT_ID=C.STUDENT_ID;

select * from student as a left join course as b on a.student_id=b.student_id
where b.student_id is null;

select * from student as a right join course as b on a.student_id=b.student_id
where a.student_id is null;

SELECT A.NAME AS MANAGER_NAME,B.NAME FROM STUDENT
AS A JOIN EMPLOYEE AS B ON A.ID=B.MANAGER_ID;

ALTER TABLE COURSE ADD COLUMN COURSE_ID INT;

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
MANAGER_ID INT
);

INSERT INTO EMPLOYEE(ID,NAME,MANAGER_ID) VALUES (101,"ADAM",103),(102,"BOB",104),(103,"CASEY",NULL),(104,"DONALD",103);

SELECT * FROM EMPLOYEE;

SELECT A.NAME AS MANAGER_NAME, B.NAME 
FROM EMPLOYEE AS A 
JOIN EMPLOYEE AS B 
ON A.ID=B.MANAGER_ID;

SELECT NAME FROM EMPLOYEE
UNION 
SELECT NAME FROM EMPLOYEE;